spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    primary:
      url : jdbc:h2:mem:sampledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
      username : sa
      password : 
      driverClassName : org.h2.Driver
    secondary:
      url : jdbc:postgresql://localhost:5432/batch2
      username : spring
      password : password
      driverClassName : org.postgresql.Driver		
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    '[com.example.demo]': debug
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace
    '[org.hibernate.type.EnumType]': trace
