spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    primary:
      url : jdbc:h2:mem:sampledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
      username : sa
      password : 
      driverClassName : org.h2.Driver
    secondary:
      url : jdbc:postgresql://localhost:5432/batch2
      username : spring
      password : password
      driverClassName : org.postgresql.Driver		

logging:
  level:
    '[com.example.demo]': debug
